// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: passport.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录 =============================================
// 账号 + 密码登录
type LoginWithAccountPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string  `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Code     *string `protobuf:"bytes,3,opt,name=Code,proto3,oneof" json:"Code,omitempty"`
}

func (x *LoginWithAccountPasswordRequest) Reset() {
	*x = LoginWithAccountPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithAccountPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithAccountPasswordRequest) ProtoMessage() {}

func (x *LoginWithAccountPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithAccountPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithAccountPasswordRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{0}
}

func (x *LoginWithAccountPasswordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginWithAccountPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginWithAccountPasswordRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

type LoginWithAccountPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *LoginWithAccountPasswordResponse) Reset() {
	*x = LoginWithAccountPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithAccountPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithAccountPasswordResponse) ProtoMessage() {}

func (x *LoginWithAccountPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithAccountPasswordResponse.ProtoReflect.Descriptor instead.
func (*LoginWithAccountPasswordResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{1}
}

func (x *LoginWithAccountPasswordResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 邮箱 + 密码登录
type LoginWithEmailPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string  `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string  `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Code     *string `protobuf:"bytes,3,opt,name=Code,proto3,oneof" json:"Code,omitempty"`
}

func (x *LoginWithEmailPasswordRequest) Reset() {
	*x = LoginWithEmailPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithEmailPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithEmailPasswordRequest) ProtoMessage() {}

func (x *LoginWithEmailPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithEmailPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithEmailPasswordRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{2}
}

func (x *LoginWithEmailPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginWithEmailPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginWithEmailPasswordRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

type LoginWithEmailPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *LoginWithEmailPasswordResponse) Reset() {
	*x = LoginWithEmailPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithEmailPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithEmailPasswordResponse) ProtoMessage() {}

func (x *LoginWithEmailPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithEmailPasswordResponse.ProtoReflect.Descriptor instead.
func (*LoginWithEmailPasswordResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{3}
}

func (x *LoginWithEmailPasswordResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 邮箱 + 验证码登录
type LoginWithEmailCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *LoginWithEmailCodeRequest) Reset() {
	*x = LoginWithEmailCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithEmailCodeRequest) ProtoMessage() {}

func (x *LoginWithEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*LoginWithEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{4}
}

func (x *LoginWithEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginWithEmailCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginWithEmailCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *LoginWithEmailCodeResponse) Reset() {
	*x = LoginWithEmailCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithEmailCodeResponse) ProtoMessage() {}

func (x *LoginWithEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*LoginWithEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{5}
}

func (x *LoginWithEmailCodeResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 手机 + 密码登录
type LoginWithMobilePasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region   string  `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	Mobile   string  `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password string  `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Code     *string `protobuf:"bytes,4,opt,name=Code,proto3,oneof" json:"Code,omitempty"`
}

func (x *LoginWithMobilePasswordRequest) Reset() {
	*x = LoginWithMobilePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithMobilePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithMobilePasswordRequest) ProtoMessage() {}

func (x *LoginWithMobilePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithMobilePasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithMobilePasswordRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{6}
}

func (x *LoginWithMobilePasswordRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LoginWithMobilePasswordRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginWithMobilePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginWithMobilePasswordRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

type LoginWithMobilePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *LoginWithMobilePasswordResponse) Reset() {
	*x = LoginWithMobilePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithMobilePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithMobilePasswordResponse) ProtoMessage() {}

func (x *LoginWithMobilePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithMobilePasswordResponse.ProtoReflect.Descriptor instead.
func (*LoginWithMobilePasswordResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{7}
}

func (x *LoginWithMobilePasswordResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 手机 + 验证码登录
type LoginWithMobileCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	Mobile string `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Code   string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *LoginWithMobileCodeRequest) Reset() {
	*x = LoginWithMobileCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithMobileCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithMobileCodeRequest) ProtoMessage() {}

func (x *LoginWithMobileCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithMobileCodeRequest.ProtoReflect.Descriptor instead.
func (*LoginWithMobileCodeRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{8}
}

func (x *LoginWithMobileCodeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LoginWithMobileCodeRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginWithMobileCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginWithMobileCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *LoginWithMobileCodeResponse) Reset() {
	*x = LoginWithMobileCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithMobileCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithMobileCodeResponse) ProtoMessage() {}

func (x *LoginWithMobileCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithMobileCodeResponse.ProtoReflect.Descriptor instead.
func (*LoginWithMobileCodeResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{9}
}

func (x *LoginWithMobileCodeResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 注册 =============================================
// 账号 + 密码注册
type RegisterWithAccountPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *RegisterWithAccountPasswordRequest) Reset() {
	*x = RegisterWithAccountPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWithAccountPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithAccountPasswordRequest) ProtoMessage() {}

func (x *RegisterWithAccountPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithAccountPasswordRequest.ProtoReflect.Descriptor instead.
func (*RegisterWithAccountPasswordRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterWithAccountPasswordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterWithAccountPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterWithAccountPasswordRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterWithAccountPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *RegisterWithAccountPasswordResponse) Reset() {
	*x = RegisterWithAccountPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWithAccountPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithAccountPasswordResponse) ProtoMessage() {}

func (x *RegisterWithAccountPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithAccountPasswordResponse.ProtoReflect.Descriptor instead.
func (*RegisterWithAccountPasswordResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterWithAccountPasswordResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 邮箱 + 验证码注册
type RegisterWithEmailCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string  `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Code     string  `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Password *string `protobuf:"bytes,3,opt,name=Password,proto3,oneof" json:"Password,omitempty"`
}

func (x *RegisterWithEmailCodeRequest) Reset() {
	*x = RegisterWithEmailCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWithEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithEmailCodeRequest) ProtoMessage() {}

func (x *RegisterWithEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterWithEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterWithEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterWithEmailCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterWithEmailCodeRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type RegisterWithEmailCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *RegisterWithEmailCodeResponse) Reset() {
	*x = RegisterWithEmailCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWithEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithEmailCodeResponse) ProtoMessage() {}

func (x *RegisterWithEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterWithEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterWithEmailCodeResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 手机号 + 验证码注册
type RegisterWithMobileCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region   string  `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	Mobile   string  `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Code     string  `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Password *string `protobuf:"bytes,4,opt,name=Password,proto3,oneof" json:"Password,omitempty"`
}

func (x *RegisterWithMobileCodeRequest) Reset() {
	*x = RegisterWithMobileCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWithMobileCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithMobileCodeRequest) ProtoMessage() {}

func (x *RegisterWithMobileCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithMobileCodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterWithMobileCodeRequest) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterWithMobileCodeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterWithMobileCodeRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterWithMobileCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterWithMobileCodeRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type RegisterWithMobileCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
}

func (x *RegisterWithMobileCodeResponse) Reset() {
	*x = RegisterWithMobileCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWithMobileCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithMobileCodeResponse) ProtoMessage() {}

func (x *RegisterWithMobileCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithMobileCodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterWithMobileCodeResponse) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterWithMobileCodeResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_passport_proto protoreflect.FileDescriptor

var file_passport_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x73, 0x0a, 0x1f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x20, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x1d, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x17,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x3e, 0x0a, 0x1e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x45, 0x0a, 0x19, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3a, 0x0a, 0x1a, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x1e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x1f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x1a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3b, 0x0a, 0x1b, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x22, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43,
	0x0a, 0x23, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57,
	0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3d, 0x0a, 0x1d, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x1d, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01,
	0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3e,
	0x0a, 0x1e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x92,
	0x06, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x65, 0x0a, 0x18, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5f, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x13,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74,
	0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5f, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x69, 0x74,
	0x68, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_passport_proto_rawDescOnce sync.Once
	file_passport_proto_rawDescData = file_passport_proto_rawDesc
)

func file_passport_proto_rawDescGZIP() []byte {
	file_passport_proto_rawDescOnce.Do(func() {
		file_passport_proto_rawDescData = protoimpl.X.CompressGZIP(file_passport_proto_rawDescData)
	})
	return file_passport_proto_rawDescData
}

var file_passport_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_passport_proto_goTypes = []interface{}{
	(*LoginWithAccountPasswordRequest)(nil),     // 0: pb.LoginWithAccountPasswordRequest
	(*LoginWithAccountPasswordResponse)(nil),    // 1: pb.LoginWithAccountPasswordResponse
	(*LoginWithEmailPasswordRequest)(nil),       // 2: pb.LoginWithEmailPasswordRequest
	(*LoginWithEmailPasswordResponse)(nil),      // 3: pb.LoginWithEmailPasswordResponse
	(*LoginWithEmailCodeRequest)(nil),           // 4: pb.LoginWithEmailCodeRequest
	(*LoginWithEmailCodeResponse)(nil),          // 5: pb.LoginWithEmailCodeResponse
	(*LoginWithMobilePasswordRequest)(nil),      // 6: pb.LoginWithMobilePasswordRequest
	(*LoginWithMobilePasswordResponse)(nil),     // 7: pb.LoginWithMobilePasswordResponse
	(*LoginWithMobileCodeRequest)(nil),          // 8: pb.LoginWithMobileCodeRequest
	(*LoginWithMobileCodeResponse)(nil),         // 9: pb.LoginWithMobileCodeResponse
	(*RegisterWithAccountPasswordRequest)(nil),  // 10: pb.RegisterWithAccountPasswordRequest
	(*RegisterWithAccountPasswordResponse)(nil), // 11: pb.RegisterWithAccountPasswordResponse
	(*RegisterWithEmailCodeRequest)(nil),        // 12: pb.RegisterWithEmailCodeRequest
	(*RegisterWithEmailCodeResponse)(nil),       // 13: pb.RegisterWithEmailCodeResponse
	(*RegisterWithMobileCodeRequest)(nil),       // 14: pb.RegisterWithMobileCodeRequest
	(*RegisterWithMobileCodeResponse)(nil),      // 15: pb.RegisterWithMobileCodeResponse
}
var file_passport_proto_depIdxs = []int32{
	0,  // 0: pb.Passport.LoginWithAccountPassword:input_type -> pb.LoginWithAccountPasswordRequest
	2,  // 1: pb.Passport.LoginWithEmailPassword:input_type -> pb.LoginWithEmailPasswordRequest
	4,  // 2: pb.Passport.LoginWithEmailCode:input_type -> pb.LoginWithEmailCodeRequest
	6,  // 3: pb.Passport.LoginWithMobilePassword:input_type -> pb.LoginWithMobilePasswordRequest
	8,  // 4: pb.Passport.LoginWithMobileCode:input_type -> pb.LoginWithMobileCodeRequest
	10, // 5: pb.Passport.RegisterWithAccountPassword:input_type -> pb.RegisterWithAccountPasswordRequest
	12, // 6: pb.Passport.RegisterWithEmailCode:input_type -> pb.RegisterWithEmailCodeRequest
	14, // 7: pb.Passport.RegisterWithMobileCode:input_type -> pb.RegisterWithMobileCodeRequest
	1,  // 8: pb.Passport.LoginWithAccountPassword:output_type -> pb.LoginWithAccountPasswordResponse
	3,  // 9: pb.Passport.LoginWithEmailPassword:output_type -> pb.LoginWithEmailPasswordResponse
	5,  // 10: pb.Passport.LoginWithEmailCode:output_type -> pb.LoginWithEmailCodeResponse
	7,  // 11: pb.Passport.LoginWithMobilePassword:output_type -> pb.LoginWithMobilePasswordResponse
	9,  // 12: pb.Passport.LoginWithMobileCode:output_type -> pb.LoginWithMobileCodeResponse
	11, // 13: pb.Passport.RegisterWithAccountPassword:output_type -> pb.RegisterWithAccountPasswordResponse
	13, // 14: pb.Passport.RegisterWithEmailCode:output_type -> pb.RegisterWithEmailCodeResponse
	15, // 15: pb.Passport.RegisterWithMobileCode:output_type -> pb.RegisterWithMobileCodeResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_passport_proto_init() }
func file_passport_proto_init() {
	if File_passport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_passport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithAccountPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithAccountPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithEmailPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithEmailPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithEmailCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithEmailCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithMobilePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithMobilePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithMobileCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginWithMobileCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWithAccountPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWithAccountPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWithEmailCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWithEmailCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWithMobileCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWithMobileCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_passport_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_passport_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_passport_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_passport_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_passport_proto_msgTypes[14].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_passport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_passport_proto_goTypes,
		DependencyIndexes: file_passport_proto_depIdxs,
		MessageInfos:      file_passport_proto_msgTypes,
	}.Build()
	File_passport_proto = out.File
	file_passport_proto_rawDesc = nil
	file_passport_proto_goTypes = nil
	file_passport_proto_depIdxs = nil
}
