// Code generated by goctl. DO NOT EDIT!
// Source: passport.proto

package server

import (
	"context"

	"tinkdance/service/passport/rpc/internal/logic"
	"tinkdance/service/passport/rpc/internal/svc"
	"tinkdance/service/passport/rpc/pb"
)

type PassportServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPassportServer
}

func NewPassportServer(svcCtx *svc.ServiceContext) *PassportServer {
	return &PassportServer{
		svcCtx: svcCtx,
	}
}

func (s *PassportServer) LoginWithAccountPassword(ctx context.Context, in *pb.LoginWithAccountPasswordRequest) (*pb.LoginWithAccountPasswordResponse, error) {
	l := logic.NewLoginWithAccountPasswordLogic(ctx, s.svcCtx)
	return l.LoginWithAccountPassword(in)
}

func (s *PassportServer) LoginWithEmailPassword(ctx context.Context, in *pb.LoginWithEmailPasswordRequest) (*pb.LoginWithEmailPasswordResponse, error) {
	l := logic.NewLoginWithEmailPasswordLogic(ctx, s.svcCtx)
	return l.LoginWithEmailPassword(in)
}

func (s *PassportServer) LoginWithEmailCode(ctx context.Context, in *pb.LoginWithEmailCodeRequest) (*pb.LoginWithEmailCodeResponse, error) {
	l := logic.NewLoginWithEmailCodeLogic(ctx, s.svcCtx)
	return l.LoginWithEmailCode(in)
}

func (s *PassportServer) LoginWithMobilePassword(ctx context.Context, in *pb.LoginWithMobilePasswordRequest) (*pb.LoginWithMobilePasswordResponse, error) {
	l := logic.NewLoginWithMobilePasswordLogic(ctx, s.svcCtx)
	return l.LoginWithMobilePassword(in)
}

func (s *PassportServer) LoginWithMobileCode(ctx context.Context, in *pb.LoginWithMobileCodeRequest) (*pb.LoginWithMobileCodeResponse, error) {
	l := logic.NewLoginWithMobileCodeLogic(ctx, s.svcCtx)
	return l.LoginWithMobileCode(in)
}

func (s *PassportServer) RegisterWithAccountPassword(ctx context.Context, in *pb.RegisterWithAccountPasswordRequest) (*pb.RegisterWithAccountPasswordResponse, error) {
	l := logic.NewRegisterWithAccountPasswordLogic(ctx, s.svcCtx)
	return l.RegisterWithAccountPassword(in)
}

func (s *PassportServer) RegisterWithEmailCode(ctx context.Context, in *pb.RegisterWithEmailCodeRequest) (*pb.RegisterWithEmailCodeResponse, error) {
	l := logic.NewRegisterWithEmailCodeLogic(ctx, s.svcCtx)
	return l.RegisterWithEmailCode(in)
}

func (s *PassportServer) RegisterWithMobileCode(ctx context.Context, in *pb.RegisterWithMobileCodeRequest) (*pb.RegisterWithMobileCodeResponse, error) {
	l := logic.NewRegisterWithMobileCodeLogic(ctx, s.svcCtx)
	return l.RegisterWithMobileCode(in)
}
